### ISSUE TITLE
철현님 질문있습니다!!!

### ISSUE THREAD

**Issue by kimwonyong** [chul-hyun/Task#1]
https://github.com/vomvoru/Task/blob/53467a3761aea916b23c9d5c0582cb2873a09498/src/components/Layout/withIsBoxComponent.tsx#L5

아래와 같이 중간에 빈 파라미터 받는 함수를 빼고 코드를 작성할 수 있을거 같은데, 
중간에 빈 파라미터를 받는 함수를 넣은 이유가 있을까요?

```
const withIsBoxComponent = <OrgProps, JSXProps = OrgProps>(
  WrappedComponent: React.ComponentType<OrgProps>,
) =>
```

**Comment by vomvoru** [comment]
특별한 이유는 없이 개발중 남겨진 사항입니다.
이전에는 defaultProps 값을 받아보기도 해서 남겨진 공간입니다.

hoc + 데코레이터 까지 해보고 필요없다면 삭제해야 겠네요. 감사합니다 👍
